server:
  port: 8080

spring:
  datasource: # 数据库配置
    url: jdbc:mysql://127.0.0.1:3306/iwork?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始大小，最大，最小
      initial-size: 3
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
  # 应用名称
  application:
    name: config-client

  # Redis配置
  redis:
    database : 0  # 连接的那个数据库
    host: 127.0.0.1 # redis服务的ip地址
    port: 6379 # redis端口号
    password:   # redis的密码，没设置过密码，可为空

  # 邮箱配置
  mail:
    host: smtp.163.com #SMTP服务器地址
    #登陆账号
    username: 15294183759
    #登陆密码（或授权码）
    password: OXYZAEYYEXJMMYAH
    properties:
      from: 15294183759@163.com #邮件发信人（即真实邮箱）
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量

  # 阿里短信配置
  sms:
    accessKeyId: LTAI4FzNm49bU7zfgZQhr3kJ
    accessKeySecret: QvaxxIOUpMnfJ8ees6T6xZLF1F3vZ5
    templateCode: SMS_211001436 #短信模板,即在阿里云短信服务中自己创建的短信模板ID
    signName: 陈陈学习  #短信签名,即最前面在【】这个中的文字

# mybatis-plus配置
mybatis-plus:
  # MyBatis Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cym.*.entity
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    # 关闭MP3.0自带的banner
    banner: false
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    # 表名是否使用下划线命名，默认数据库表使用下划线命名
    table-underline: true
    db-config:
      #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_UUID
# Logger Config 日志打印配置
logging:
  level:
    com.cym.springboot: debug